FROM elasticsearch:7.3.1

ARG BRANCH

# Put the synonyms file into the container and assign read permissions
ADD https://raw.githubusercontent.com/HumanExposure/factotum_elastic/"${BRANCH}"/chemical_synonyms.txt /usr/share/elasticsearch/config/chemical_synonyms.txt
USER root
RUN chown elasticsearch:root  /usr/share/elasticsearch/config/chemical_synonyms.txt \
 && chmod 644 /usr/share/elasticsearch/config/chemical_synonyms.txt
USER elasticsearch