FROM logstash:6.7.2

ENV MYSQL_CONNECTOR_VERSION="5.1.47"

ADD --chown=logstash "https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${MYSQL_CONNECTOR_VERSION}.jar" /opt/mysql-connector.jar
ADD --chown=logstash ./pipelines/* /usr/share/logstash/pipeline/

RUN rm /usr/share/logstash/pipeline/logstash.conf
