# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadocument',
            name='data_group',
        ),
        migrations.RemoveField(
            model_name='datagroup',
            name='csv',
        ),
        migrations.DeleteModel(
            name='DataDocument',
        ),
    ]
