# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_datasource_estimated_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='state',
            field=models.CharField(choices=[('AT', 'Awaiting Triage'), ('IP', 'In Progress'), ('CO', 'Complete'), ('ST', 'Stale')], default='AT', max_length=2),
        ),
    ]
