# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0002_datasource_estimated_records")]

    operations = [
        migrations.CreateModel(
            name="DataGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "downloaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("extraction_script", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="datasource",
            name="state",
            field=models.CharField(
                choices=[
                    ("AT", "Awaiting Triage"),
                    ("IP", "In Progress"),
                    ("CO", "Complete"),
                    ("ST", "Stale"),
                ],
                default="AT",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="datagroup",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.DataSource"
            ),
        ),
    ]
