# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171121_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='csv',
            field=models.FileField(default=1, upload_to='csv/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='downloaded_at',
            field=models.DateTimeField(),
        ),
    ]
