# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171205_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('product_category', models.CharField(blank=True, max_length=50, null=True)),
                ('matched', models.BooleanField(default=False)),
                ('extracted', models.BooleanField(default=False)),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DataGroup')),
            ],
        ),
    ]
