# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171207_1354'),
        ('dashboard', '0009_datadocument'),
    ]

    operations = [
    ]
