# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171212_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
