# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_datagroup_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LO', 'Low')], default='HI', max_length=2),
        ),
    ]
