# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20171207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagroup',
            name='extraction_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ExtractionScript'),
        ),
    ]
