# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20171207_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagroup',
            name='extraction_script',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
