# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20171227_0912'),
        ('dashboard', '0013_auto_20171226_1034'),
    ]

    operations = [
    ]
