# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0015_auto_20171230_1017")]

    operations = [migrations.RemoveField(model_name="productdocument", name="upc")]
