# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_auto_20180110_1308"),
        ("dashboard", "0017_auto_20180115_1611"),
    ]

    operations = []
