# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0019_auto_20180118_0745"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="last_edited_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        )
    ]
