# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0019_auto_20180118_0745")]

    operations = [
        migrations.AddField(
            model_name="datadocument",
            name="data_source",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.DataSource",
            ),
            preserve_default=False,
        )
    ]
