# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_productcategory_last_edited_by"),
        ("dashboard", "0020_extracted_text_chem"),
    ]

    operations = []
