# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_datadocument_data_source"),
        ("dashboard", "0020_productcategory_last_edited_by"),
    ]

    operations = []
