# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_merge_20180119_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagroup',
            old_name='extraction_script',
            new_name='download_script',
        ),
    ]
