# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_merge_20180120_1203"),
        ("dashboard", "0022_auto_20180119_1944"),
    ]

    operations = []
