# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20180120_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionscript',
            name='qa_begun',
            field=models.BooleanField(default=False),
        ),
    ]
