# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 00:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_extractionscript_qa_begun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()])),
                ('qa_begun', models.BooleanField(default=False)),
                ('script_type', models.CharField(choices=[('DL', 'download'), ('EX', 'extraction'), ('PC', 'product categorization')], default='EX', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='download_script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='extraction_script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
        migrations.DeleteModel(
            name='ExtractionScript',
        ),
    ]
