# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0026_auto_20180305_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='puc_assigned_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
        migrations.AddField(
            model_name='product',
            name='puc_assigned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='puc_assigned_usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
