# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0027_auto_20180307_1222")]

    operations = [
        migrations.RemoveField(model_name="extractedchemical", name="extracted_text"),
        migrations.RemoveField(model_name="extractedtext", name="data_document"),
        migrations.RemoveField(model_name="extractedtext", name="extraction_script"),
        migrations.DeleteModel(name="ExtractedChemical"),
        migrations.DeleteModel(name="ExtractedText"),
    ]
