# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20180307_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedchemical',
            name='point_composition',
        ),
        migrations.RemoveField(
            model_name='extractedchemical',
            name='reported_functional_use',
        ),
        migrations.RemoveField(
            model_name='extractedtext',
            name='id',
        ),
        migrations.RemoveField(
            model_name='extractedtext',
            name='qa_checked',
        ),
        migrations.AddField(
            model_name='extractedchemical',
            name='report_funcuse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='prod_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='record_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='cas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='chem_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='raw_max_comp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='raw_min_comp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='data_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.DataDocument'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='doc_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='extraction_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='rev_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
