# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20180313_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250, null=True),
        ),
    ]
