# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20180313_1104'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DSSToxSubstance',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('true_cas', models.CharField(blank=True, max_length=50, null=True)),
        #         ('true_chemname', models.CharField(blank=True, max_length=500, null=True)),
        #         ('rid', models.CharField(blank=True, max_length=50, null=True)),
        #         ('sid', models.CharField(blank=True, max_length=50, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True, null=True)),
        #     ],
        # ),
        migrations.RenameField(
            model_name='extractedchemical',
            old_name='cas',
            new_name='raw_cas',
        ),
        migrations.RenameField(
            model_name='extractedchemical',
            old_name='chem_name',
            new_name='raw_chem_name',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='download_script',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
        # migrations.AddField(
        #     model_name='dsstoxsubstance',
        #     name='extracted_chemical',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ExtractedChemical'),
        # ),
    ]
