# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20180313_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagroup',
            name='download_script',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
    ]
