# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_dsstoxsubstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedchemical',
            old_name='cas',
            new_name='raw_cas',
        ),
        migrations.RenameField(
            model_name='extractedchemical',
            old_name='chem_name',
            new_name='raw_chem_name',
        ),
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
