# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_product_manufacturer'),
        ('dashboard', '0030_auto_20180322_0955'),
    ]

    operations = [
    ]
