# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_auto_20180322_0955"),
        ("dashboard", "0031_auto_20180322_1622"),
    ]

    operations = []
