# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script')),
            ],
        ),
        migrations.AddField(
            model_name='datadocument',
            name='qa_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.QAGroup'),
        ),
    ]
