# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:29
from __future__ import unicode_literals

import dashboard.models.extracted_chemical
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0035_auto_20180411_0919")]

    operations = [
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ("title",)},
        ),
        migrations.CreateModel(
            name="WeightFractionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="datadocument", options={"ordering": ["-id"]}
        ),
        migrations.AddField(
            model_name="extractedchemical",
            name="ingredient_rank",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    dashboard.models.extracted_chemical.validate_ingredient_rank
                ],
            ),
        ),
        migrations.AddField(
            model_name="extractedchemical",
            name="raw_central_comp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="extractedchemical",
            name="units",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dashboard.UnitType"
            ),
        ),
    ]
