# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20180419_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedchemical',
            old_name='units',
            new_name='unit_type',
        ),
        migrations.AddField(
            model_name='extractedchemical',
            name='weight_fraction_type',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.WeightFractionType'),
        ),
    ]
