# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0037_auto_20180420_1624")]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"ordering": ["-created_at"]}
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["gen_cat", "prod_fam", "prod_type"],
                "verbose_name_plural": "Product categories",
            },
        ),
        migrations.AlterModelOptions(
            name="weightfractiontype", options={"ordering": ("id",)}
        ),
    ]
