# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20180424_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadocument',
            name='source_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='dashboard.SourceType'),
            preserve_default=False,
        ),
    ]
