# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 10:40
from __future__ import unicode_literals

# import dashboard.models.ingredient
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0039_auto_20180430_1240")]

    operations = [
        migrations.CreateModel(
            name="DSSToxSubstanceToIngredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "dsstox_substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.DSSToxSubstance",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "lower_wf_analysis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=16,
                        null=True,
                        # validators=[dashboard.models.ingredient.validate_wf_analysis],
                    ),
                ),
                (
                    "central_wf_analysis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=16,
                        null=True,
                        # validators=[dashboard.models.ingredient.validate_wf_analysis],
                    ),
                ),
                (
                    "upper_wf_analysis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        max_digits=16,
                        null=True,
                        # validators=[dashboard.models.ingredient.validate_wf_analysis],
                    ),
                ),
                (
                    "dsstox_substances",
                    models.ManyToManyField(
                        through="dashboard.DSSToxSubstanceToIngredient",
                        to="dashboard.DSSToxSubstance",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProductToIngredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.Ingredient",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.Product",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="ingredient",
            name="products",
            field=models.ManyToManyField(
                through="dashboard.ProductToIngredient", to="dashboard.Product"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="weight_fraction_type",
            field=models.ForeignKey(
                default="1",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dashboard.WeightFractionType",
            ),
        ),
        migrations.AddField(
            model_name="dsstoxsubstancetoingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.Ingredient"
            ),
        ),
        migrations.AddField(
            model_name="dsstoxsubstance",
            name="ingredients",
            field=models.ManyToManyField(
                through="dashboard.DSSToxSubstanceToIngredient",
                to="dashboard.DSSToxSubstance",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.ManyToManyField(
                through="dashboard.ProductToIngredient", to="dashboard.Ingredient"
            ),
        ),
    ]
