# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 15:47
from __future__ import unicode_literals

import dashboard.models.ingredient
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20180430_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lower_wf_analysis', models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True, validators=[dashboard.models.ingredient.validate_wf_analysis])),
                ('central_wf_analysis', models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True, validators=[dashboard.models.ingredient.validate_wf_analysis])),
                ('upper_wf_analysis', models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True, validators=[dashboard.models.ingredient.validate_wf_analysis])),
                ('dsstox_substance', models.ManyToManyField(to='dashboard.DSSToxSubstance')),
                ('product', models.ManyToManyField(to='dashboard.Product')),
                ('weight_fraction_type', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.WeightFractionType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

