# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSSToxSubstanceIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dsstox_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DSSToxSubstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='dsstox_substance',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.AddField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ingredient'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product'),
        ),
        migrations.AddField(
            model_name='dsstoxsubstanceingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ingredient'),
        ),
        migrations.AddField(
            model_name='dsstoxsubstance',
            name='ingredients',
            field=models.ManyToManyField(through='dashboard.DSSToxSubstanceIngredient', to='dashboard.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dsstox_substances',
            field=models.ManyToManyField(through='dashboard.DSSToxSubstanceIngredient', to='dashboard.DSSToxSubstance'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='products',
            field=models.ManyToManyField(through='dashboard.ProductIngredient', to='dashboard.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='dashboard.ProductIngredient', to='dashboard.Ingredient'),
        ),
    ]