# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0041_datadocument_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='qa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('APPROVED_WITHOUT_ERROR', 'Approved without errors'), ('APPROVED_WITH_ERROR', 'Approved with errors')], default=None, max_length=30, null=True),
        ),
    ]
