# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20180508_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='qa_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='extracted_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='dashboard.ExtractedText'),
        ),
    ]
