# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20180518_1416'),
        ('dashboard', '0042_auto_20180521_1705'),
    ]

    operations = [
    ]
