# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0045_auto_20180531_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='qa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('APPROVED_WITHOUT_ERROR', 'Approved without errors'), ('APPROVED_WITH_ERROR', 'Approved with errors')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='extracted_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='dashboard.ExtractedText'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='raw_cas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raw CAS'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='raw_chem_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Raw chemical name'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='raw_max_comp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raw maximum composition'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='raw_min_comp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raw minimum composition'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='report_funcuse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reported functional use'),
        ),
    ]
