# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_qa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='qa_edited',
            field=models.BooleanField(default=False),
        ),
    ]
