# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20180608_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='group_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.GroupType',
                                    blank=True, null=True),
        ),
    ]
