# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-08 09:28
from __future__ import unicode_literals

from django.db import migrations
from dashboard.models.group_type import GroupType
from dashboard.models.document_type import DocumentType




class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0048_datagroup_group_type'),
    ]

    operations = [
       
    ]
