# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20180608_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagroup',
            name='group_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.GroupType'),
        ),
    ]
