# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20180620_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadocument',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=False),
        ),
    ]
