# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0051_auto_20180620_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='qa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='QA approved by'),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QA approval date'),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_edited',
            field=models.BooleanField(default=False, verbose_name='QA edited'),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('APPROVED_WITHOUT_ERROR', 'Approved without errors'), ('APPROVED_WITH_ERROR', 'Approved with errors')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='qa_checked',
            field=models.BooleanField(default=False, verbose_name='QA approved'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='qa_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.QAGroup', verbose_name='QA group'),
        ),
    ]
