# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20180627_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='QANotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('qa_notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='extractedtext',
            name='qa_notes',
        ),
        migrations.AddField(
            model_name='qanotes',
            name='extracted_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ExtractedText'),
        ),
    ]
