# Generated by Django 2.0.8 on 2018-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_auto_20180809_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadocument',
            old_name='product_category',
            new_name='raw_category',
        ),
        migrations.AddField(
            model_name='datagroup',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
