# Generated by Django 2.0.7 on 2018-09-12 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20180824_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='fs_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
