# Generated by Django 2.0.7 on 2018-09-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_remove_datadocument_uploaded_at'),
        ('dashboard', '0062_datagroup_fs_id'),
    ]

    operations = [
    ]
