# Generated by Django 2.0.7 on 2018-09-26 15:45

import dashboard.models.data_group
from django.db import migrations, models
from dashboard.models.group_type import GroupType
from dashboard.models.document_type import DocumentType

def create_default_document_type(apps, schema_editor):
    # create the default "unidentified" document_type
    DocumentType.objects.create(title='Unidentified', description='Unidentified Document Type', group_type_id=1)

    docs = apps.get_model('dashboard', 'DataDocument')
    for dd in docs.objects.all():
        dd.document_type_id = 1
        dd.save()


def create_default_data_group_type(apps, schema_editor):
    # create the default "unidentified" group_type
    GroupType.objects.create(title='Unidentified', code='UN', description='Unidentified Group Type')

    data_group = apps.get_model('dashboard', 'DataGroup')
    for dg in data_group.objects.all():
        dg.group_type_id = 1
        dg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_datagroup_fs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='code',
            field=models.TextField(default='UN'),
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='csv',
            field=models.FileField(null=True, upload_to=dashboard.models.data_group.csv_upload_path),
        ),
        migrations.RunPython(create_default_data_group_type),
        migrations.RunPython(create_default_document_type),
    ]

