# Generated by Django 2.0.8 on 2018-10-04 10:00

import dashboard.models.data_group
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_datagroup_fs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='PUC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.PUC'),
        )
    ]
