# Generated by Django 2.0.7 on 2018-09-28 12:34

import dashboard.models.data_group
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_datagroup_fs_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCPCat',
            fields=[
                ('extractedtext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.ExtractedText')),
                ('cat_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cat Code')),
                ('description_cpcat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description CPCat')),
                ('cpcat_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPCat Code')),
                ('cpcat_sourcetype', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPCat SourceType')),
            ],
            options={
                'abstract': False,
            },
            bases=('dashboard.extractedtext',),
        ),
        migrations.CreateModel(
            name='ExtractedListPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('raw_cas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raw CAS')),
                ('raw_chem_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Raw chemical name')),
                ('extracted_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='dashboard.ExtractedCPCat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grouptype',
            name='code',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='csv',
            field=models.FileField(null=True, upload_to=dashboard.models.data_group.csv_upload_path),
        ),
    ]
