# Generated by Django 2.0.7 on 2018-09-26 17:28

import dashboard.models.data_group
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_datagroup_fs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='code',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='csv',
            field=models.FileField(null=True, upload_to=dashboard.models.data_group.csv_upload_path),
        ),
    ]
