# Generated by Django 2.0.9 on 2018-10-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20180927_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
