# Generated by Django 2.1.2 on 2018-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20181003_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
