# Generated by Django 2.1.2 on 2018-11-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_auto_20181108_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttopuc',
            name='puc_assigned_time',
        ),
    ]
