# Generated by Django 2.1.2 on 2018-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_producttopuc_puc_assigned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanotes',
            name='qa_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
