# Generated by Django 2.1.2 on 2018-11-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_producttopuc_puc_assigned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='extracted_chemical',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ExtractedChemical'),
        ),
    ]
