# Generated by Django 2.1.2 on 2018-12-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20181205_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='extracted_chemical',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curated_chemical', to='dashboard.ExtractedChemical'),
        ),
    ]
