# Generated by Django 2.1.2 on 2018-12-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20181204_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanotes',
            name='extracted_text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ExtractedText'),
        ),
    ]
