# Generated by Django 2.1.2 on 2019-02-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_add_dsstox_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='rawchem_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_curated_chemical', to='dashboard.RawChem'),
        ),
        migrations.RunSQL(
            """
            UPDATE dashboard_rawchem rc 
            INNER JOIN  
            dashboard_dsstoxlookup dss on 
            rc.raw_chem_name = dss.true_chemname  
            SET rc.dsstox_id = dss.id
            """
        )
    ]
