# Generated by Django 2.1.2 on 2019-02-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_add_dsstox_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='rawchem_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_curated_chemical', to='dashboard.RawChem'),
        ),
        migrations.RunSQL(
            """
            UPDATE dashboard_rawchem rc 
            inner join dashboard_dsstoxsubstance sub on 
            rc.id = sub.rawchem_ptr_id
            inner join dashboard_dsstoxlookup dss
            on dss.sid = sub.sid 
            SET dsstox_id = dss.id
            """,
        reverse_sql="UPDATE dashboard_rawchem SET dsstox_id = NULL"
        )
    ]
