# Generated by Django 2.1.7 on 2019-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_puc_name_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcpcat',
            name='cpcat_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPCat Code'),
        ),
    ]
