# Generated by Django 2.1.2 on 2019-02-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20190213_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='prod_fam',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='puc',
            name='prod_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
