# Generated by Django 2.1.2 on 2019-02-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_rawchem_extracted_text_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedchemical',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='extracted_cpcat',
        ),
    ]
