# Generated by Django 2.1.2 on 2019-02-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_remove_extractedchild_et'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawchem',
            old_name='extracted_text_new',
            new_name='extracted_text',
        ),
    ]
