# Generated by Django 2.1.2 on 2019-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_extractedhh_doc_and_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawchem',
            name='temp_id',
        ),
        migrations.RemoveField(
            model_name='rawchem',
            name='temp_obj_name',
        ),
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='sid',
            field=models.CharField(max_length=50, unique=True, verbose_name='DTXSID'),
        ),
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='true_cas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='True CAS'),
        ),
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='true_chemname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='True chemical name'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='hhe_report_number',
            field=models.CharField(max_length=30, verbose_name='HHE report number'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='naics_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NAICS code'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_age',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Age of population'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'All-male population'), ('FEMALE', 'All-female population'), ('BOTH', 'Both male and female population')], max_length=75, null=True, verbose_name='Gender of population'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other description of population'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='sampling_date',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Date of sampling'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='study_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Study location'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='analytical_method',
            field=models.TextField(blank=True, null=True, verbose_name='Analytical method'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='num_measure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeric measure'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='num_nondetect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeric nondetect'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='sampling_method',
            field=models.TextField(blank=True, null=True, verbose_name='Sampling method'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='doc_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Document date'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='prod_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='rev_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revision number'),
        ),
        migrations.AlterField(
            model_name='rawchem',
            name='rid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RID'),
        ),
    ]
