# Generated by Django 2.1.2 on 2019-02-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_rename_rawchem_et'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawchem',
            name='extracted_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawchem', to='dashboard.ExtractedText'),
        ),
    ]
