# Generated by Django 2.1.7 on 2019-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0090_extractedhh_doc_and_rec")]

    operations = [
        migrations.AddField(
            model_name="datadocument",
            name="note",
            field=models.TextField(blank=True, null=True),
        )
    ]
