# Generated by Django 2.1.2 on 2019-02-26 02:08

import dashboard.models.extracted_chemical
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_dd_note_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedchemical',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedchemical',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='rawchem',
            name='temp_id',
        ),
        migrations.RemoveField(
            model_name='rawchem',
            name='temp_obj_name',
        ),
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='sid',
            field=models.CharField(max_length=50, unique=True, verbose_name='DTXSID'),
        ),
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='true_cas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='True CAS'),
        ),
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='true_chemname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='True chemical name'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='ingredient_rank',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[dashboard.models.extracted_chemical.validate_ingredient_rank], verbose_name='Ingredient rank'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.UnitType', verbose_name='Unit type'),
        ),
        migrations.AlterField(
            model_name='extractedchemical',
            name='weight_fraction_type',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.WeightFractionType', verbose_name='Weight fraction type'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='hhe_report_number',
            field=models.CharField(max_length=30, verbose_name='HHE report number'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='naics_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NAICS code'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_age',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Age of population'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'All-male population'), ('FEMALE', 'All-female population'), ('BOTH', 'Both male and female population')], max_length=75, null=True, verbose_name='Gender of population'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other description of population'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='sampling_date',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Date of sampling'),
        ),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='study_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Study location'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='analytical_method',
            field=models.TextField(blank=True, null=True, verbose_name='Analytical method'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='num_measure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeric measure'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='num_nondetect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeric nondetect'),
        ),
        migrations.AlterField(
            model_name='extractedhhrec',
            name='sampling_method',
            field=models.TextField(blank=True, null=True, verbose_name='Sampling method'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='data_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extracted_text', serialize=False, to='dashboard.DataDocument'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='doc_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Document date'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='prod_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='rev_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revision number'),
        ),
        migrations.AlterField(
            model_name='rawchem',
            name='rid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RID'),
        ),
    ]
