# Generated by Django 2.1.2 on 2019-02-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_dd_note_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedchemical',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedchemical',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='raw_chem_name_old',
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='data_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extracted_text', serialize=False, to='dashboard.DataDocument'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='doc_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Document date'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='prod_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='rev_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revision number'),
        ),
    ]
