# Generated by Django 2.1.2 on 2019-03-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_puc_to_tag_assumed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttopuc',
            unique_together={('product', 'puc', 'classification_method')},
        ),
    ]
