# Generated by Django 2.1.7 on 2019-03-04 02:11

from django.db import migrations, models

def remove_hh_gender_strings(apps, schema_editor):
    '''
    This clears any previously stored <chars> on prod
    ...w/o doing this the migration will not succeed if there have been
    texts longer than 2 chars because it won't truncate previous longer string.
    I doubt that any of them are set yet anyway, cause there is no way to enter
    them in the interface.
    '''
    ExtractedHHDoc = apps.get_model('dashboard', 'ExtractedHHDoc')
    for rec in ExtractedHHDoc.objects.all():
        rec.population_gender = ''
        rec.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_puc_to_tag_assumed'),
    ]

    operations = [
        migrations.RunPython(remove_hh_gender_strings,
                                reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='extractedhhdoc',
            name='population_gender',
            field=models.CharField(blank=True, choices=[('BO', 'Both'), ('FM', 'Female'), ('MA', 'Male')], max_length=2, null=True, verbose_name='Gender of Population'),
        ),
    ]
