# Generated by Django 2.1.7 on 2019-03-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0093_gender_choice_field")]

    operations = [
        migrations.AlterUniqueTogether(
            name="producttopuc",
            unique_together={("product", "puc", "classification_method")},
        )
    ]
