# Generated by Django 2.1.2 on 2019-03-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0097_script_confidence")]

    operations = [
        migrations.AddField(
            model_name="extractedlistpresence",
            name="qa_flag",
            field=models.BooleanField(default=False),
        )
    ]
