# Generated by Django 2.1.2 on 2019-03-20 09:06

from django.db import migrations, models
import django.db.models.deletion

from django.apps import apps

def get_default_extractionscript():
    Script = apps.get_model('dashboard', 'Script')
    ex = Script.objects.filter(title='Manual (dummy)').filter(script_type='EX').first()
    return ex.id

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_add_cpcat_qa_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qagroup',
            name='extraction_script',
            field=models.ForeignKey(default=get_default_extractionscript(), blank=False, limit_choices_to={'script_type': 'EX'}, null=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
    ]
