# Generated by Django 2.1.2 on 2019-03-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_add_cpcat_qa_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qagroup',
            name='extraction_script',
            field=models.ForeignKey(blank=True, limit_choices_to={'script_type': 'EX'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
    ]
