# Generated by Django 2.1.2 on 2019-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_document_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedchemical',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedchemical',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedfunctionaluse',
            name='raw_chem_name_old',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='raw_cas_old',
        ),
        migrations.RemoveField(
            model_name='extractedlistpresence',
            name='raw_chem_name_old',
        ),
    ]
