# Generated by Django 2.2.1 on 2019-05-03 15:58

from django.db import migrations
from django.core.management import call_command

def load_fixture_data(apps, schema_editor):
    call_command('loaddata', '14_list_presence_tag.yaml', app_label='dashboard')

def remove_fixture_data(apps, schema_editor):
    extracted_list_presence_tags = apps.get_model('dashboard', 'ExtractedListPresenceTag')
    for tag in extracted_list_presence_tags.objects.all():
        tag.delete()

class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0105_document_subtitle'),
    ]
    operations = [
        migrations.RunPython(load_fixture_data, reverse_code=remove_fixture_data)
    ]

