# Generated by Django 2.2 on 2019-04-29 11:38

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_document_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeGroupTypeCompatibilty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DocumentType')),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.GroupType')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Document type/Group type compatibilty',
                'verbose_name_plural': 'Document type/Group type compatibilties',
                'unique_together': {('document_type', 'group_type')},
            },
        ),
    ]
