# Generated by Django 2.2.1 on 2019-05-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_PUC_tag_downloadable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadocument',
            name='extracted',
        ),
    ]
