# Generated by Django 2.2.1 on 2019-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_extractedlistpresencetagdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawchem',
            name='raw_chem_name',
            field=models.CharField(blank=True, max_length=1300, null=True, verbose_name='Raw chemical name'),
        ),
    ]
