# Generated by Django 2.2.2 on 2019-06-14 15:29

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0114_long_rawchemname")]

    operations = [
        migrations.AlterModelOptions(
            name="extractedchemical",
            options={
                "ordering": (
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("ingredient_rank"),
                        nulls_last=True,
                    ),
                )
            },
        )
    ]
