# Generated by Django 2.2.1 on 2019-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_url_on_dd_dg_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptype',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
