# Generated by Django 2.2.1 on 2019-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_longer_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedchemical',
            name='report_funcuse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Functional use'),
        ),
    ]
