# Generated by Django 2.2.1 on 2019-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_raw_chem_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptype',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
