# Generated by Django 2.2.4 on 2019-08-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0120_auto_20190712_1054")]

    operations = [migrations.RemoveField(model_name="product", name="data_source")]
