# Generated by Django 2.2.1 on 2019-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0121_unit_type_nullable")]

    operations = [
        migrations.AlterField(
            model_name="grouptype",
            name="code",
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        )
    ]
