# Generated by Django 2.2.1 on 2019-09-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0122_remove_product_data_source")]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="rawchem_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="dashboard.RawChem",
            ),
        )
    ]
