# Generated by Django 2.2.1 on 2019-09-11 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0123_remove_parent_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='url',
            field=models.CharField(blank=True, max_length=375, null=True,
                                   validators=[django.core.validators.URLValidator()]),
        ),
    ]
