# Generated by Django 2.2.1 on 2019-10-23 10:47

import dashboard.models.dsstox_lookup
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0132_auditlog_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsstoxlookup',
            name='sid',
            field=models.CharField(max_length=50, unique=True,
                                   validators=[dashboard.models.dsstox_lookup.validate_prefix,
                                               dashboard.models.dsstox_lookup.validate_blank_char],
                                   verbose_name='DTXSID'),
        ),
    ]
