# Generated by Django 2.2.6 on 2019-11-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0138_field_names")]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_key", "model_name", "field_name"],
                name="dashboard_a_object__bdfb42_idx",
            ),
        ),
    ]
