version: '3.5'


volumes:
  sqldata:
  esdata:
  lsdata:
  kibanadata:
  kibanaoptdata:
  factotumwsstatic:


services:
  mysql:
    image: mysql:5.7.23
    restart: unless-stopped
    environment:
      MYSQL_USER: "${SQL_USER:-factotum}"
      MYSQL_PASSWORD: "${SECRET_KEY}"
      MYSQL_DATABASE: "${SQL_DATABASE:-factotum}"
      MYSQL_ROOT_PASSWORD: "${SECRET_KEY}"
    ports:
      - 3306:3306
    volumes: 
      - type: volume
        source: sqldata
        target: /var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --wait-timeout=${SQL_CONF_WAIT_TIMEOUT:-28800}
      --interactive-timeout=${SQL_CONF_INTERACTIVE_TIMEOUT:-28800}
      --innodb_buffer_pool_size=${SQL_CONF_INNODB_BUFFER_POOL_SIZE:-128M}
      --innodb_log_buffer_size=${SQL_CONF_INNODB_LOG_BUFFER_SIZE:-1M}
      --max_connections=${SQL_CONF_MAX_CONNECTIONS:-151}
      --key_buffer_size=${SQL_CONF_KEY_BUFFER_SIZE:-8388608}
      --innodb_ft_cache_size=${SQL_CONF_INNODB_FT_CACHE_SIZE:-8000000}
      --innodb_ft_total_cache_size=${SQL_CONF_INNODB_FT_TOTAL_CACHE_SIZE:-640000000}
      --thread_stack=${SQL_CONF_THREAD_STACK:-262144}
      --sort_buffer_size=${SQL_CONF_SORT_BUFFER_SIZE:-262144}
      --read_buffer_size=${SQL_CONF_READ_BUFFER_SIZE:-131072}
      --read_rnd_buffer_size=${SQL_CONF_READ_RND_BUFFER_SIZE:-262144}
      --max_heap_table_size=${SQL_CONF_MAX_HEAP_TABLE_SIZE:-16777216}
      --tmp_table_size=${SQL_CONF_TMP_TABLE_SIZE:-16777216}
      --bulk_insert_buffer_size=${SQL_CONF_BULK_INSERT_BUFFER_SIZE:-8388608}
      --join_buffer_size=${SQL_CONF_JOIN_BUFFER_SIZE:-262144}
      --net_buffer_length=${SQL_CONF_NET_BUFFER_LENGTH:-16384}
      --innodb_sort_buffer_size=${SQL_CONF_INNODB_SORT_BUFFER_SIZE:-1M}
      --binlog_cache_size=${SQL_CONF_BINLOG_CACHE_SIZE:-32K}
      --binlog_stmt_cache_size=${SQL_CONF_BINLOG_STMT_CACHE_SIZE:-32K}

  elasticsearch:
    image: elasticsearch:6.7.2
    restart: unless-stopped
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.monitoring.enabled: "false"
      ES_JAVA_OPTS: "-Xms${ES_MEMORY_LIMIT:-1g} -Xmx${ES_MEMORY_LIMIT:-1g}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data

  kibana:
    image: kibana:6.7.2
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: kibanadata
        target: /usr/share/kibana/data
      - type: volume
        source: kibanaoptdata
        target: /usr/share/kibana/optimize
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: .
      dockerfile: ../../dockerfiles/Dockerfile.logstash
      args:
        MYSQL_CONNECTOR_VERSION: ${MYSQL_CONNECTOR_VERSION:-8.0.17}
        BRANCH: ${FACTOTUM_ELASTIC_BRANCH:-dev}
    image: factotum-logstash
    restart: "no"
    environment:
      ELASTICSEARCH_HOST: elasticsearch:9200
      SQL_DATABASE: "${SQL_DATABASE:-factotum}"
      SQL_USER: "${SQL_USER:-factotum}"
      SQL_PASSWORD: "${SECRET_KEY}"
      SQL_HOST: mysql
      SQL_PORT: 3306
      XPACK_MONITORING_ENABLED: "false"
      LS_JAVA_OPTS: "-Xms${LS_MEMORY_LIMIT:-1g} -Xmx${LS_MEMORY_LIMIT:-1g}"
    volumes:
      - type: volume
        source: lsdata
        target: /usr/share/logstash/data
    depends_on:
      - elasticsearch
      - mysql

  factotum-ws:
    build:
      context: .
      dockerfile: ../../dockerfiles/Dockerfile.factotum_ws
      args:
        BUILD_TYPE: ${FACTOTUM_WS_BUILD_TYPE:-prod}
        BRANCH: ${FACTOTUM_WS_BRANCH:-dev}
    image: factotum-ws
    restart: unless-stopped
    environment:
      FLASK_SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: development
      FLASK_DEBUG: "true"
      SQL_HOST: mysql
      SQL_USER: "${SQL_USER:-factotum}"
      SQL_PASSWORD: "${SECRET_KEY}"
      SQL_DATABASE: "${SQL_DATABASE:-factotum}"
      GUNICORN_CMD_ARGS: ${FACTOTUM_WS_GUNICORN_CMD_ARGS:---bind=0.0.0.0:5000 --workers=3 --forwarded-allow-ips="*"}
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: factotumwsstatic
        target: /app/static
    depends_on:
      - mysql
