# Generated by Django 2.2.6 on 2019-11-01 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elastic", "0003_fix_puc_in_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                (
                    "application",
                    models.CharField(choices=[("FA", "factotum")], max_length=2),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.PositiveIntegerField(null=True)),
            ],
        )
    ]
